[package]
name = "feruca"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Theo Beers <theo.beers@fu-berlin.de>"]

[dependencies]
bincode = "1.3.3"
once_cell = "1.12.1"
serde = { version = "1.0.138", features = ["derive"] }
unicode-canonical-combining-class = { git = "https://github.com/theodore-s-beers/unicode-canonical-combining-class" }
unicode-normalization = "0.1.21"
