[package]
name = "feruca"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Theo Beers <theo.beers@fu-berlin.de>"]
repository = "https://github.com/theodore-s-beers/feruca"
description = "An implementation of the Unicode Collation Algorithm"
keywords = ["Unicode", "collation", "sorting"]
categories = ["algorithms", "internationalization", "text-processing"]

[dependencies]
bincode = "1.3.3"
once_cell = "1.13.0"
serde = { version = "1.0.138", features = ["derive"] }
unicode-canonical-combining-class = { git = "https://github.com/theodore-s-beers/unicode-canonical-combining-class" }
unicode-normalization = "0.1.21"
