[package]
name = "feruca"
version = "0.2.4"
edition = "2021"
license = "MIT"
authors = ["Theo Beers <theo.beers@fu-berlin.de>"]
repository = "https://github.com/theodore-s-beers/feruca"
description = "An implementation of the Unicode Collation Algorithm"
keywords = ["Unicode", "collation", "sorting"]
categories = ["algorithms", "internationalization", "text-processing"]
exclude = ["/test-data/"]

[dependencies]
bincode = "1.3.3"
bstr = "0.2.17"
once_cell = "1.13.0"
serde = { version = "1.0.139", features = ["derive"] }
tinyvec = { version = "1.6.0", features = ["serde"] }
unicode-canonical-combining-class = "0.4.0"

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
name = "conformance"
harness = false
