[package]
name = "feruca"
version = "0.7.1"
edition = "2021"
license = "MIT"
authors = ["Theo Beers <theo.beers@fu-berlin.de>"]
repository = "https://github.com/theodore-s-beers/feruca"
description = "An implementation of the Unicode Collation Algorithm"
keywords = ["Unicode", "collation", "sorting"]
categories = ["algorithms", "internationalization", "text-processing"]
exclude = ["/test-data/"]

[dependencies]
bincode = "1.3.3"
bstr = "1.2.0"
once_cell = "1.17.1"
rustc-hash = "1.1.0"
unicode-canonical-combining-class = "0.5.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "conformance"
harness = false
